pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('iyyoba') // Jenkins credentials ID
        DOCKER_IMAGE_NAME = "iyyoba/shopping_cart"   // Docker Hub repo name
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/iyyoba/Year2_Period4.git'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean compile'
            }
        }

        stage('Unit Tests') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Package') {
            steps {
                sh 'mvn package'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t shopping_cart:latest .'
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'iyyoba', usernameVariable: 'iyyoba', passwordVariable: 'jenkins-pipeline')]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                    sh 'docker push iyyoba/shopping_cart:latest'
                }
            }
        }
    }
}